In [ ]:
## pandas
 .  Python ki librray
 .  pandas deals all types of data
 .  backend Numpy

In [ ]:
  Pandas Data Structure
>    Pandas Series
>    pandas  data frame

In [ ]:
pandas  series :
                 data in single column (univariate )

In [ ]:
!pip install pandas

In [4]:
import pandas as pd

In [6]:
# creating series
s1 = pd.Series([10,20,30,40,50])

In [23]:
s1.dtype

dtype('int64')

In [ ]:
component :    index, values, dtype

In [10]:
s2  = pd.Series(["headpone", "laptop", "mouse", "spekaer", "keybard"])

In [15]:
len(s2)

5

In [16]:
s2.shape

(5,)

In [ ]:
# Indexing

In [17]:
s2[1]

'laptop'

In [19]:
s2[0]

'headpone'

In [22]:
s2[4]

'keybard'

In [25]:
s2

0    headpone
1      laptop
2       mouse
3     spekaer
4     keybard
dtype: object

In [26]:
# slicing

In [27]:
s2[0:3]

0    headpone
1      laptop
2       mouse
dtype: object

In [51]:
s2[1:2]

1    laptop
dtype: object

In [35]:
s2

0    headpone
1      laptop
2       mouse
3     spekaer
4     keybard
dtype: object

In [ ]:
label:  abhi index by defualt (0,1,2,3) mai khud define kr skta hon

In [44]:
fruit  = pd.Series(data = [10,20, 30,40,50,60,70],  index=["Apple", "banana", "peach", "orange", "pineapple", "gava", "mango"])

In [50]:
fruit["Apple": "gava"]

Apple        10
banana       20
peach        30
orange       40
pineapple    50
gava         60
dtype: int64

In [53]:
fruit["orange"]

np.int64(40)

In [ ]:
#   DataFrame
             data mai aik sai zyada column ho to data frame bn jata hai   ( multivariate)

In [88]:
data = {
    "name" : ['Usman', "Arham", "saad", "hassan", 'Anus ', "kashif"],
    "Rool_no" : [109, 102, 143, 890, 786, 876],
    "Python":  [90, 40, 50, 60, 78, 44,],
    "pandas":   [ 89, 56,100, 45, 67, 98 ],
    "math":  [19,45,67,88,99,70]
}

In [89]:
data = pd.DataFrame(data)

In [90]:
data

     name  Rool_no  Python  pandas  math
0   Usman      109      90      89    19
1   Arham      102      40      56    45
2    saad      143      50     100    67
3  hassan      890      60      45    88
4   Anus       786      78      67    99
5  kashif      876      44      98    70

In [91]:
# columns:
    Accesing a column
    Acces more then one columns
    add a column
    del a column

IndentationError: unexpected indent (849700760.py, line 2)

In [92]:
# Acess a column

In [93]:
data["Rool_no"]

0    109
1    102
2    143
3    890
4    786
5    876
Name: Rool_no, dtype: int64

In [94]:
data.Rool_no

0    109
1    102
2    143
3    890
4    786
5    876
Name: Rool_no, dtype: int64

In [95]:
data.name

0     Usman
1     Arham
2      saad
3    hassan
4     Anus
5    kashif
Name: name, dtype: object

In [96]:
data.math

0    19
1    45
2    67
3    88
4    99
5    70
Name: math, dtype: int64

In [77]:
# More then 1 columns

In [97]:
data[["Rool_no", 'math', 'pandas']]

   Rool_no  math  pandas
0      109    19      89
1      102    45      56
2      143    67     100
3      890    88      45
4      786    99      67
5      876    70      98

In [98]:
data[["name"]]

     name
0   Usman
1   Arham
2    saad
3  hassan
4   Anus
5  kashif

In [ ]:
# add a column
obt/total X 100

In [118]:
data["total"]=data.Python+ data.math+data.pandas

In [122]:
data["percenta ge"]=data.total/ 300*100

In [123]:
data["Grade"]=['A' if p>=70
 else  'B'  if p>=60
 else 'C' if p>= 50
 else 'F' for p in data.percentage]

In [129]:
data.sort_values(ascending=True, by = 'Grade')

     name  Rool_no  Python  pandas  math  total  percentage   percentage Grade
2    saad      143      50     100    67    217    72.333333   72.333333     A
4   Anus       786      78      67    99    244    81.333333   81.333333     A
5  kashif      876      44      98    70    212    70.666667   70.666667     A
0   Usman      109      90      89    19    198    66.000000   66.000000     B
3  hassan      890      60      45    88    193    64.333333   64.333333     B
1   Arham      102      40      56    45    141    47.000000   47.000000     F

In [131]:
data["result "]=[ "pass" if i =="A"  else 'Fail' for i in data.Grade]

In [ ]:
axis = 1  --- col
axis = 0   --- row

In [136]:
data = data.drop(['Rool_no'], axis = 0)

KeyError: "['Rool_no'] not found in axis"

In [138]:
data = data.drop(['name'], axis = 1)

In [139]:
data

   Python  pandas  math  total  percentage   percentage Grade result
0      90      89    19    198    66.000000   66.000000     B    Fail
1      40      56    45    141    47.000000   47.000000     F    Fail
2      50     100    67    217    72.333333   72.333333     A    pass
3      60      45    88    193    64.333333   64.333333     B    Fail
4      78      67    99    244    81.333333   81.333333     A    pass
5      44      98    70    212    70.666667   70.666667     A    pass