In [2]:
import pandas as pd

In [ ]:
# !pip install pandas

In [4]:
data = pd.read_excel('employee.xlsx')

In [ ]:
data.head()  # display 5 rows by default

In [ ]:
data.head(12)

In [ ]:
data.tail()

In [ ]:
data.sample(2)

In [ ]:
data.sample(4)

# Slicing

In [ ]:
data[2:6]

In [ ]:
data[row, col]  -- data[s:e, s:e]

In [ ]:
data[0:7, 0:]

In [ ]:
pandas  --- 2d

### Iloc and loc

In [ ]:
data[row, col]  -- data[s:e, s:e]

In [ ]:
data.iloc[2:9, 1:3]

In [ ]:
data.iloc[0:12, 3:]

In [ ]:
# rows 2: 8 ,  Designtaion ,Department, Age

In [10]:
data.head()

   Serial  Emp_ID Designation Department   Age    Salary
0       1    1101     Manager   Accounts  50.0  200000.0
1       2    1107     Officer         IT  30.0   80000.0
2       3    1203     Officer         HR  28.0       NaN
3       4    1005     Manager         HR  45.0  120000.0
4       5    2123  Office Boy   Accounts  27.0   45000.0

In [ ]:
data.iloc[2:8, 2:5]

In [ ]:
data.loc[2:8,'Designation':'Age']

In [ ]:
data.loc[[6,3,0,1,9],['Age','Salary','Emp_ID']]

In [11]:
data = pd.read_excel('employee.xlsx', header=None)
data.head()

        0       1            2           3    4       5
0  Serial  Emp_ID  Designation  Department  Age  Salary
1       1    1101      Manager    Accounts   50  200000
2       2    1107      Officer          IT   30   80000
3       3    1203      Officer          HR   28     NaN
4       4    1005      Manager          HR   45  120000

In [12]:
data.iloc[4:8, 2:4]

            2         3
4     Manager        HR
5  Office Boy  Accounts
6  Accountant       NaN
7  Accountant  Accounts

In [13]:
data = pd.read_excel('employee.xlsx',)
data.head()

   Serial  Emp_ID Designation Department   Age    Salary
0       1    1101     Manager   Accounts  50.0  200000.0
1       2    1107     Officer         IT  30.0   80000.0
2       3    1203     Officer         HR  28.0       NaN
3       4    1005     Manager         HR  45.0  120000.0
4       5    2123  Office Boy   Accounts  27.0   45000.0

In [16]:
data.loc[[3,5,7,9,13], ['Department','Salary']]

    Department    Salary
3           HR  120000.0
5          NaN  100000.0
7           IT   75000.0
9   Production   89000.0
13          IT  100000.0

In [19]:
data

    Serial  Emp_ID Designation  Department   Age    Salary
0        1    1101     Manager    Accounts  50.0  200000.0
1        2    1107     Officer          IT  30.0   80000.0
2        3    1203     Officer          HR  28.0       NaN
3        4    1005     Manager          HR  45.0  120000.0
4        5    2123  Office Boy    Accounts  27.0   45000.0
5        6    2451  Accountant         NaN  34.0  100000.0
6        7    1111  Accountant    Accounts   NaN  110000.0
7        8    1001     Officer          IT  25.0   75000.0
8        9    1234     Manager          IT  23.0       NaN
9       10    2156    Engineer  Production  45.0   89000.0
10      11    6543     Officer  Production  29.0  100000.0
11      12    3214  Accountant     Account  49.0  123000.0
12      13    2156    Engineer  Production  45.0   89000.0
13      14    1098     Officer          IT  25.0  100000.0
14      15    2912     Officer          IT  31.0   90000.0
15      16    1222     Officer         NaN  25.0       NaN
16      17    2156    Engineer  Production  45.0   89000.0
17      18    2123  Office Boy    Accounts  27.0   45000.0
18      19    1005     Manager          HR  45.0  120000.0
19      20    2123  Office Boy    Accounts  27.0   45000.0
20      21    6543     Officer  Production  29.0  100000.0
21      22    3214  Accountant     Account  49.0  123000.0
22      23    2156    Engineer  Production  45.0   89000.0
23      24    1098     Officer          IT  25.0  100000.0
24      25    2156    Engineer  Production  45.0   89000.0
25      26    2123  Office Boy    Accounts  27.0   45000.0

In [18]:
data[data.Designation=='Manager']

    Serial  Emp_ID Designation Department   Age    Salary
0        1    1101     Manager   Accounts  50.0  200000.0
3        4    1005     Manager         HR  45.0  120000.0
8        9    1234     Manager         IT  23.0       NaN
18      19    1005     Manager         HR  45.0  120000.0

In [20]:
data[data.Designation=='Accountant']

    Serial  Emp_ID Designation Department   Age    Salary
5        6    2451  Accountant        NaN  34.0  100000.0
6        7    1111  Accountant   Accounts   NaN  110000.0
11      12    3214  Accountant    Account  49.0  123000.0
21      22    3214  Accountant    Account  49.0  123000.0

# Fatch all the employees working in HR department

In [ ]:
data[data.Department=='HR']

In [ ]:
# All the employees with age greater than 30.
data[data.Age>30]

In [ ]:
# employe with salary less than equal to 100k
data[data.Salary<=100000]

In [ ]:
# Engineers with salary less than or equal to 100k
data[(data.Designation=='Engineer')&(data.Salary<=100000)]

In [26]:
# Fetch empployee with age greater than 45 or Designation Accountant
data[(data.Age>45) | (data.Designation=='Accountant')]

    Serial  Emp_ID Designation Department   Age    Salary
0        1    1101     Manager   Accounts  50.0  200000.0
5        6    2451  Accountant        NaN  34.0  100000.0
6        7    1111  Accountant   Accounts   NaN  110000.0
11      12    3214  Accountant    Account  49.0  123000.0
21      22    3214  Accountant    Account  49.0  123000.0

In [29]:
# What is the max salary in company
data.Salary.max()

np.float64(200000.0)

In [30]:
# What is the min salary in company
data.Salary.min()

np.float64(45000.0)

In [31]:
# What is the Average salary in company
data.Salary.mean()

np.float64(94173.91304347826)

#### Fetch the employee with salary less than average salary

In [ ]:
data[data.Salary< data.Salary.mean()]

#### Fetch the employee with salary greater than average salary

In [ ]:
data[data.Salary>data.Salary.mean()]

In [38]:
data.describe(include='all')

,Serial,Emp_ID,Designation,Department,Age,Salary
count,26.000000,26.000000,26,24,25.000000,23.000000
unique,NaN,NaN,5,5,NaN,NaN
top,NaN,NaN,Officer,Production,NaN,NaN
freq,NaN,NaN,9,7,NaN,NaN
mean,13.500000,2166.692308,NaN,NaN,35.000000,94173.913043
std,7.648529,1463.539074,NaN,NaN,9.746794,33714.917354
min,1.000000,1001.000000,NaN,NaN,23.000000,45000.000000
25%,7.250000,1108.000000,NaN,NaN,27.000000,84500.000000
50%,13.500000,2123.000000,NaN,NaN,30.000000,90000.000000
75%,19.750000,2156.000000,NaN,NaN,45.000000,105000.000000
max,26.000000,6543.000000,NaN,NaN,50.000000,200000.000000